title: Buddelsee West Marches
description: Wiki zu meiner West Marches-Kampagne im Sandbox-Setting "die Buddelsee. Diese Seite befindet sich aktuell noch im Aufbau
theme: just-the-docs

url: https://CallithRocksfall.github.io/BuddelseeWestMarches
logo: "/assets/logo.png"
favicon_ico: "/assets/favicon.png"


aux_links:
  Cairn SRD: https://cairnrpg.com/

callouts:
  info:
    color: yellow
  insight:
    color: blue

